// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJOh15QCBsF23Z-wBm5-SkbrTn_8aMG_U',
    appId: '1:218086322843:web:fd82a287d7ff8508b6cc3e',
    messagingSenderId: '218086322843',
    projectId: 'food-delivery-5b298',
    authDomain: 'food-delivery-5b298.firebaseapp.com',
    storageBucket: 'food-delivery-5b298.firebasestorage.app',
    measurementId: 'G-SZZTDV9N2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLRJsNIrTN4GaKzdO7RV4oHKGj5ZH_ZTM',
    appId: '1:218086322843:android:5fc889ee55e129abb6cc3e',
    messagingSenderId: '218086322843',
    projectId: 'food-delivery-5b298',
    storageBucket: 'food-delivery-5b298.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwMiIgsBiBWy0izBqMSlBVuxGj3fDH7_o',
    appId: '1:218086322843:ios:343a9bdc711ff9afb6cc3e',
    messagingSenderId: '218086322843',
    projectId: 'food-delivery-5b298',
    storageBucket: 'food-delivery-5b298.firebasestorage.app',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwMiIgsBiBWy0izBqMSlBVuxGj3fDH7_o',
    appId: '1:218086322843:ios:343a9bdc711ff9afb6cc3e',
    messagingSenderId: '218086322843',
    projectId: 'food-delivery-5b298',
    storageBucket: 'food-delivery-5b298.firebasestorage.app',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJOh15QCBsF23Z-wBm5-SkbrTn_8aMG_U',
    appId: '1:218086322843:web:c1162571457c7a58b6cc3e',
    messagingSenderId: '218086322843',
    projectId: 'food-delivery-5b298',
    authDomain: 'food-delivery-5b298.firebaseapp.com',
    storageBucket: 'food-delivery-5b298.firebasestorage.app',
    measurementId: 'G-NMEJX1BKFY',
  );
}
